#!/usr/bin/env bash

echo "Compiling and installing ssh-roads ..."
cargo install --path .

echo "Creating command links ..."
sudo ln -sf "$(which ssh-roads)" /usr/local/bin/roads

echo "Configuring ~/.ssh-roads ..."
mkdir -p ~/.ssh-roads

# Use -f to ensure that the old links could be overwritten if this script be run multiple times.
ln -sf "$PWD/servers.json" ~/.ssh-roads/servers.json
ln -sf "$PWD/.env" ~/.ssh-roads/.env

echo "✅ Installation complete! You can now run 'ssh-roads' or 'roads' from anywhere."
